LECDIR := $(abspath $(PWD))
LECHOME := $(abspath $(LECDIR)/..)

NOTEBOOKS := \
  0-outline.ipynb \
  1-logical-operations.ipynb \
  2-if-statements.ipynb \
  3-lists.ipynb \
  4-looping.ipynb \
  5-file-io.ipynb

all: ${NOTEBOOKS}

include $(LECHOME)/defaults.mk
