touch multi1.cpp
touch multi2.cpp
touch array1.cpp
touch array2.cpp
touch perf1.cpp
touch perf2.cpp
touch array3a.cpp
touch array3b.cpp
touch array4a.cpp
touch array4b.cpp
touch array5.cpp
touch array6a.cpp
touch array6b.cpp
touch array6c.cpp
touch array7.cpp
touch array8.cpp
touch array9.cpp
touch array10a.cpp
touch array10b.cpp
touch accumulate.cpp
