LECDIR := $(abspath $(PWD))
LECHOME := $(abspath $(LECDIR)/..)

NOTEBOOKS := \
  0-python-containers.ipynb \
  1-dictionaries.ipynb \
  2-tuples.ipynb \
  3-sets.ipynb \
  4-example.ipynb

all: ${NOTEBOOKS}

include $(LECHOME)/defaults.mk
