LECDIR := $(abspath $(PWD))
LECHOME := $(abspath $(LECDIR)/..)

NOTEBOOKS := \
  0-interacting-with-python.ipynb \
  1-values-variables-types.ipynb \
  2-strings.ipynb \
  3-numbers.ipynb \

all: ${NOTEBOOKS}

include $(LECHOME)/defaults.mk
