LECDIR := $(abspath $(PWD))
LECHOME := $(abspath $(LECDIR)/..)

#DEFAULT_GOAL := all

NOTEBOOKS := \
  0-outline.ipynb \
  1-values-variables-types.ipynb \
  2-strings.ipynb \
  3-numbers.ipynb \


all: ${NOTEBOOKS}

include $(LECHOME)/defaults.mk
