LECDIR := $(abspath $(PWD))
LECHOME := $(abspath $(LECDIR)/..)

NOTEBOOKS := \
  0-python-object-model.ipynb \
  1-python-modules.ipynb \
  2-python-exceptions.ipynb

all: ${NOTEBOOKS}

include $(LECHOME)/defaults.mk
