touch MyVector1.cpp
touch MyVector1.hpp
touch MyVector2.cpp
touch MyVector2.hpp
touch func.cpp
touch increment.cpp
touch increment.cpp
touch main1.cpp
touch main2.cpp
touch new1.cpp
touch new2.cpp
touch new3.cpp
touch new4.cpp
touch new5.cpp
touch pointer1.cpp
touch pointer2.cpp
touch pointer3.cpp
touch pointer4.cpp
touch pointer5.cpp
touch stack1.cpp
touch stack2.cpp
touch stack3.cpp
touch stack4.cpp
touch stack5.cpp
